version: '3'

services:
  zoo1:
    image: zookeeper:3.7
    container_name: zoo1
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=kafka1
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
    ports:
      - 9092
    depends_on:
      - zoo1

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_HOST_NAME=kafka2
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
    ports:
      - 9092
    depends_on:
      - zoo1

  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ADVERTISED_HOST_NAME=kafka3
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
    ports:
      - 9092
    depends_on:
      - zoo1
